learning_users/basic_app/urls.py
from django.urls import path
from basic_app import views

app_name = "basic_app"

urlpatterns = [
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
]

learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('', views.index, name='index'),
    path('basic_app/', include('basic_app.urls')),
    path('admin/', admin.site.urls),
]

learning_users/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE)

    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to = "profile_pics",blank=True)

    def __str__(self):
        return self.user.username

learning_users/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):

    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

learning_users/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm, UserProfileInfoForm

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request,"basic_app/index.html")

def register(request):
    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()
            registered = True

        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,"basic_app/registration.html",
                            {"registered":registered,
                            "user_form":user_form,
                            "profile_form":profile_form})

def user_login(request):

    if request.method == "POST":

        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse('Account is not active')
        else:
            print("Someone tried to login and failed!")
            return HttpResponse("Invalid login details!")

    else:
        return render(request,"basic_app/login.html",{})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

learning_users/templates/basic_app/4 wars/wars.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>wars</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
    <link rel="stylesheet" href="wars.css">
    <script
      src="https://code.jquery.com/jquery-3.5.1.js"
      integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
      crossorigin="anonymous">
    </script>
  </head>
  <body class="container">

    <h1>Welcome to Connect Four!</h1>
    <h2>The object of this game is to connect four of your chips in a row!</h2>
    <h3 class="player">Let's get started!</h3>

    <div class="buttons container">
      <tr>
        <button  type="button"></button>
        <button  type="button"></button>
        <button  type="button"></button>
        <button  type="button"></button>
        <button  type="button"></button>
        <button  type="button"></button>
        <button  type="button"></button>
      </tr><br>
      <tr>
        <button  type="button"></button>
        <button  type="button"></button>
        <button  type="button"></button>
        <button  type="button"></button>
        <button  type="button"></button>
        <button  type="button"></button>
        <button  type="button"></button>
        </tr><br>
      </tr>
      <tr>
        <button  type="button"></button>
        <button  type="button"></button>
        <button  type="button"></button>
        <button  type="button"></button>
        <button  type="button"></button>
        <button  type="button"></button>
        <button  type="button"></button>
        </tr><br>
      </tr>
      <tr>
        <button  type="button"></button>
        <button  type="button"></button>
        <button  type="button"></button>
        <button  type="button"></button>
        <button  type="button"></button>
        <button  type="button"></button>
        <button  type="button"></button>
        </tr><br>
      </tr>
      <tr>
        <button  type="button"></button>
        <button  type="button"></button>
        <button  type="button"></button>
        <button  type="button"></button>
        <button  type="button"></button>
        <button  type="button"></button>
        <button  type="button"></button>
      </tr>
      </tr><br>
      <tr>
        <button  type="button"></button>
        <button  type="button"></button>
        <button  type="button"></button>
        <button  type="button"></button>
        <button  type="button"></button>
        <button  type="button"></button>
        <button  type="button"></button>
        </tr><br>
      </tr>
    </div>




    <script src="wars.js"></script>
  </body>
</html>

learning_users/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top navbar-inverse">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'basic_app:register' %}">Register</a></li>

          {% if user.is_authenticated %}
          <li><a class="navbar-link" href="{% url "basic_app:user_logout" %}">Logout</a></li>
          {% else %}
          <li><a class="navbar-link" href="{% url "basic_app:user_login" %}">Login</a></li>
          {% endif %}

        </ul>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>

  </body>
</html>

learning_users/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block body_block %}

<div class="jumbotron">
   <h1>Django Level Five</h1>
</div>
{% endblock %}

learning_users/templates/basic_app/login.html
{% extends "basic_app/base.html" %}
{% block body_block %}

<div class="jumbotron container">
  <h1>Please Login</h1>
  <form class="" action="{% url "basic_app:user_login" %}" method="post">
    {% csrf_token %}
    <label class="col-sm-2 control-label" for="username">Username</label>
    <input class="form-group form-control" type="text" name="username" placeholder="Username">

    <label class="col-sm-2 control-label" for="password">Password</label>
    <input class="form-group form-control " type="password" name="password">

    <input class="btn btn-info btn-lg" type="submit" name="" value="Login">

  </form>
</div>

{% endblock %}

learning_users/templates/basic_app/registration.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% load static %}

{% block body_block %}
  <div class="jumbotron">
    {% if registered %}
      <h1>Thank you for registering!</h1>
    {% else %}
      <h1>Register Here</h1>
      <h3>Fill out the form</h3>
      <div class="">

      <form enctype="multipart/form-data" method="post">
        <div class="form-group">
        {% csrf_token %}
        {{user_form.as_p}}
        {{profile_form.as_p}}
        <input class="btn btn-info btn-lg" type="submit" name="" value="Register">
        </div>
      </form>

    </div>
    {% endif %}
  </div>
{% endblock %}

learning_users/templates/basic_app/test.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">

  </head>
  <body>
    <div class="jumbotron container">
      <h1>Please Login</h1>
      <form class="" action="{% url "basic_app:user_login" %}" method="post">


        <label class="col-sm-2 control-label" for="username">Username</label>
        <input class="form-group form-control" type="text" name="username" placeholder="Username">

        <label class="col-sm-2 control-label" for="password">Password</label>
        <input class="form-group form-control " type="password" name="password">

        <input class="btn btn-info btn-lg " type="submit" name="" value="Login">

      </form>
    </div>
  </body>
</html>